INCLUDE "charmap.asm"

INCLUDE "macros.asm"

INCLUDE "constants/hardware.inc"
INCLUDE "constants/gfx_constants.asm"
INCLUDE "constants/move_constants.asm"
INCLUDE "constants/input_constants.asm"
INCLUDE "constants/battle_constants.asm"
INCLUDE "constants/item_constants.asm"
INCLUDE "constants/list_constants.asm"
INCLUDE "constants/music_constants.asm"
INCLUDE "constants/event_constants.asm"
INCLUDE "constants/text_constants.asm"
INCLUDE "constants/pokedex_constants.asm"
INCLUDE "constants/pokemon_constants.asm"
INCLUDE "constants/pokemon_data_constants.asm"
INCLUDE "constants/oam_constants.asm"
INCLUDE "constants/type_constants.asm"
