; Disassembly of "pokemon-red-jp.gb"

INCLUDE "constants.asm"

INCLUDE "mgbdis/bank_001.asm"
INCLUDE "mgbdis/bank_002.asm"
INCLUDE "mgbdis/bank_003.asm"
INCLUDE "mgbdis/bank_004.asm"
INCLUDE "mgbdis/bank_005.asm"
INCLUDE "mgbdis/bank_006.asm"
INCLUDE "mgbdis/bank_007.asm"
INCLUDE "mgbdis/bank_008.asm"
INCLUDE "mgbdis/bank_009.asm"
INCLUDE "mgbdis/bank_00a.asm"
INCLUDE "mgbdis/bank_00b.asm"
INCLUDE "mgbdis/bank_00c.asm"
INCLUDE "mgbdis/bank_00d.asm"
INCLUDE "mgbdis/bank_00e.asm"
INCLUDE "mgbdis/bank_00f.asm"
INCLUDE "mgbdis/bank_010.asm"
INCLUDE "mgbdis/bank_011.asm"
INCLUDE "mgbdis/bank_012.asm"
INCLUDE "mgbdis/bank_013.asm"
INCLUDE "mgbdis/bank_014.asm"
INCLUDE "mgbdis/bank_015.asm"
INCLUDE "mgbdis/bank_016.asm"
INCLUDE "mgbdis/bank_017.asm"
INCLUDE "mgbdis/bank_018.asm"
INCLUDE "mgbdis/bank_019.asm"
INCLUDE "mgbdis/bank_01a.asm"
INCLUDE "mgbdis/bank_01b.asm"
INCLUDE "mgbdis/bank_01c.asm"
INCLUDE "mgbdis/bank_01d.asm"
INCLUDE "mgbdis/bank_01e.asm"
INCLUDE "mgbdis/bank_01f.asm"
